/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#581d87",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#283044",
        "on-surface-variant": "#464554",
        "surface-container": "#eaedff",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#141b2c",
        "background": "#faf8ff",
        "tertiary-fixed-dim": "#bfc6dd",
        "surface-container-highest": "#dae2fd",
        "surface-variant": "#dae2fd",
        "primary": "#4648d4",
        "on-primary-container": "#fffbff",
        "on-secondary-fixed-variant": "#632892",
        "surface-bright": "#faf8ff",
        "secondary-container": "#cb8ffd",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-tertiary-container": "#fefcff",
        "tertiary-fixed": "#dbe2fa",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#3f4759",
        "primary-fixed-dim": "#c0c1ff",
        "outline-variant": "#c7c4d7",
        "on-secondary-fixed": "#2d004f",
        "surface-container-high": "#e2e7ff",
        "error-container": "#ffdad6",
        "secondary": "#7c43ab",
        "tertiary": "#545c70",
        "inverse-primary": "#c0c1ff",
        "primary-container": "#6063ee",
        "tertiary-container": "#6d7489",
        "on-background": "#131b2e",
        "on-surface": "#131b2e",
        "on-error-container": "#93000a",
        "surface-container-low": "#f2f3ff",
        "secondary-fixed-dim": "#e0b6ff",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#07006c",
        "surface": "#faf8ff",
        "secondary-fixed": "#f2daff",
        "inverse-on-surface": "#eef0ff",
        "outline": "#767586",
        "surface-dim": "#d2d9f4",
        "surface-tint": "#494bd6",
        "primary-fixed": "#e1e0ff",
        // Additional dark-mode jewel tones
        "prakriti-dark": "#0b0f19",
        "prakriti-navy": "#131b2e",
        "prakriti-indigo": "#4648d4",
        "prakriti-purple": "#7c43ab",
        "prakriti-gold": "#f59e0b",
        "prakriti-teal": "#0d9488",
        "prakriti-amber": "#d97706",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "margin-mobile": "20px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "unit": "8px",
        "container-max": "1200px"
      },
      fontFamily: {
        "body-md": ["var(--font-sora)", "Sora", "sans-serif"],
        "body-lg": ["var(--font-sora)", "Sora", "sans-serif"],
        "display-lg": ["var(--font-playfair)", "Playfair Display", "serif"],
        "display-lg-mobile": ["var(--font-playfair)", "Playfair Display", "serif"],
        "headline-md": ["var(--font-playfair)", "Playfair Display", "serif"],
        "headline-sm": ["var(--font-playfair)", "Playfair Display", "serif"],
        "label-sm": ["var(--font-sora)", "Sora", "sans-serif"],
        "label-md": ["var(--font-sora)", "Sora", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display-lg-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    }
  },
  plugins: []
};
